name: f-store
version: '1.0'
summary: An ecommerce app made with flutter framework
description: |
  First snap buid of an ecommerce app 'F-store' made with flutter framework

base: core22
confinement: strict
grade: stable

apps:
  f-store:
    command: f_store
    extensions: [gnome]

parts:
  f-store:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart







# name: f-store
# version: 1.0.0
# summary: A demo E-commerce App
# description: hello world
# # description: This is an example App to explore the Snapcraft, 
# #   SnapStore and Flutter. To make These types of applications, 
# #   Contact me on UpWork

# confinement: strict
# base: core22
# grade: stable
# # icon: snap/gui/icon.png

# # slots:
# #   dbus-f-store: # adjust accordingly to your app name
# #     interface: dbus
# #     bus: session
# #     name: org.bar.f_store # adjust accordingly to your app name and
    
# apps:
#   f-store:
#     command: f_store
# #     extensions: [gnome] # gnome includes the libraries required by flutter
#     plugs:
#     - network
#     slots:
#       - dbus-f-store
# parts:
#   f-store:
#     source: .
#     plugin: flutter
#     flutter-target: lib/main.dart # The main entry-point file of the application
