name: f-store
version: "1.0.5"
summary: A demo E-commerce App
description: |
  This is an example App to explore the Snapcraft, 
  SnapStore and Flutter. To make These types of applications, 
  Contact me on UpWork:

confinement: strict
base: core22
grade: stable
icon: snap/gui/icon.png

slots:
  dbus-f-store:
    interface: dbus
    bus: session
    name: org.bar.f_store

apps:
  f-store:
    command: f_store
    extensions: [gnome]
    plugs:
      - network
    slots:
      - dbus-f-store

parts:
  f-store:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
