name: flutter-shop
version: git
summary: A e-commerce design with flutter framework
description: |
  A Simple Shopping app build with flutter framework
confinement: strict
base: core18
grade: stable

apps:
  flutter-shop:
    command: f_store
    extensions: [flutter-master]
    plugs:
      - network

parts:
  flutter-shop:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
