name: f-store
version: 1.0.0
summary: A demo E-commerce App
description: This is an example App to explore the Snapcraft,
  SnapStore and Flutter. To make These types of applications,
  Contact me on UpWork

confinement: strict
base: core24
grade: stable
icon: snap/gui/f-store.png

slots:
  dbus-f-store: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.bar.f_store # adjust accordingly to your app name and    
apps:
  f-store:
    command: f_store
    # extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
    - network
    slots:
      - dbus-f-store
parts:
  f-store:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
