name: flutter-shop
version: git
summary: A e-commerce design with flutter framework
description: |
  A Simple Shopping app build with flutter framework
confinement: strict
base: core18
grade: stable
#platforms:
#  amd64:
#  arm64:

apps:
  flutter-shop:
    command: f_store
    extensions: [ flutter-stable ]
    plugs:
    - home
    - desktop
    - desktop-legacy
    - wayland

parts:
  flutter-shop:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
