name: flutter-shop
summary: Flutter Shop
version: git
adopt-info: flutter-shop
grade: stable
confinement: strict
base: core22
#platform:
#  amd64:
#  arm64:

parts:
  flutter-shop:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart

slots:
  futter-shop:
    interface: dbus
    bus: session
    name: com.eigfa.flutter-shop

apps:
  flutter-shop:
    command: f_store
    common-id: com.eigfa.flutter-shop
    desktop: usr/share/applications/com.eigfa.flutter-shop
    extensions: [ gnome ]
